guard against using existing hydra home not created by these scripts overwrite 'hcl' each time boot us curled from the cmd-line (vs using hcl)

diff --git a/config/template/boot-two b/config/template/boot-two
--- a/config/template/boot-two
+++ b/config/template/boot-two
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+function fail() {
+	echo "aborting... $1"
+	exit
+}
+
 [ -z "${CLUSTER_HOST}" ] && export CLUSTER_HOST="{{hostname}}"
 [ -z "${IMAGE_VERSION}" ] && export IMAGE_VERSION="{{version}}"
 [ -z "${IMAGE_HOST}" ] && export IMAGE_HOST="${HYDRA_BOOT}"
@@ -11,8 +16,11 @@
 # add hydra bin dir to path so processes can inherit
 export PATH=${PATH}:${HYDRA_IMAGE}/bin
 
+# check for HYDRA home. if exists, ensure it was created by this script
+[ -d "${HYDRA_IMAGE}" ] && [ ! -d "${HYDRA_IMAGE}/.bootmagic" ] && fail "${HYDRA_IMAGE} directory not created by this script"
+
 # create required directories
-for dir in bin lib log etc/pid; do
+for dir in .bootmagic bin lib log etc/pid; do
 	dir=${HYDRA_IMAGE}/${dir}
 	[ ! -d ${dir} ] && mkdir -p ${dir} && echo "created ${dir}"
 done
@@ -35,10 +43,7 @@ done
 
 # install command line helper
 HCL=${HYDRA_IMAGE}/bin/hcl
-[ ! -f ${HCL}  ] && (
-	curl -s "http://${HYDRA_BOOT}/render/hcl?cluster=${CLUSTER_ID}&hostname=${CLUSTER_HOST}" > ${HCL} || fail "failed hcl load"
-	chmod +x ${HCL}
-)
+curl -s "http://${HYDRA_BOOT}/render/hcl?cluster=${CLUSTER_ID}&hostname=${CLUSTER_HOST}" > ${HCL} && chmod +x ${HCL} || fail "failed hcl load"
 
 # launch host local processes
 for proc in ${PROCESSES}; do
